src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Detox_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Points to Detox client when created from this record.</description>
        <label>Detox Client</label>
        <referenceTo>Detox_Client__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Detox_Client__c.object
<CustomObject>
    <fields>
        <fullName>Client_Name__c</fullName>
        <inlineHelpText>This name will not be visible to Ana Liffey</inlineHelpText>
        <label>Client Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <label>Detox Client</label>
    <nameField>
        <displayFormat>DC-{000000}</displayFormat>
        <label>Detox Client Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detox Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateDetoxClient.cls
/* 
Author: Maeve Kerney, Enclude
Purpose: Create detox record using details from Contact record
 
Called from: CreateDetoxClientPage - button on a Contact (initially Open Access only)
Tested in: TestCreateDetoxClient
*/
public with sharing class CreateDetoxClient
{
  private Contact basedOnClient;
  private Detox_Client__c detoxClient;
  
  public CreateDetoxClient(ApexPages.StandardController controller)
    {
        basedOnClient = (Contact)controller.getRecord();
        basedOnClient = [SELECT ID, Name, Birthdate, Detox_Client__c FROM Contact WHERE ID = :basedOnClient.ID];
        system.debug('Contact: ' + basedOnClient.Name + basedOnClient.Birthdate);
    }
  
  public PageReference makeDetoxClient ()
    {
        if (basedOnClient.Detox_Client__c == NULL)
        	detoxClient = newDetoxClient();
        else {
        	detoxClient = new Detox_Client__c();
        	detoxClient = [SELECT Id FROM Detox_Client__c WHERE Id = :basedOnClient.Detox_Client__c];
        	system.debug('Detox client record already created');
        }

        String detoxClientURL = '/' + detoxClient.ID + '/e?retURL=%2F' + detoxClient.ID;
        PageReference detoxClientPage = new PageReference(detoxClientURL);
        return detoxClientPage;
        
    }
        
        
  public Detox_Client__c newDetoxClient()
    {
       
       Detox_Client__c thisDetoxClient = new Detox_Client__c (Client_Name__c = basedOnClient.Name,Date_of_Birth__c = basedOnClient.Birthdate);
       insert thisDetoxClient;
       
       system.debug('Detox client: '+ thisDetoxClient);
       system.debug('basedOnClient: ' + basedOnClient);
       
       basedOnClient.Detox_Client__c = thisDetoxClient.ID;       
       update basedOnClient; 
       
       system.debug('Updated contact: ' + basedOnClient.Name + basedOnClient.Birthdate + basedOnClient.Detox_Client__c);
       
       return(thisDetoxClient);
      
    }
        
 
}